okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
    redirect-uri: "{baseUrl}/login/oauth2/code/okta"
    post-logout-redirect-uri: "{baseUrl}"