okta:
  oauth2:
    issuer: https://dev-11mkptye4o4w052e.us.auth0.com/
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
#    redirect-uri: "{BASE_URL}/login/oauth2/code/okta"
#    post-logout-redirect-uri: "{BASE_URL}"