okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
    redirect-uri: ${OKTA_REDIRECT_URI}
    post-logout-redirect-uri: ${OKTA_LOGOUT_URI}